parameters:
  - name: poolNameTemplate
    type: string
  - name: sourceBranch
    type: string
    default: "refs/heads/master"
  - name: serviceName
    type: string
  - name: azureSubscriptionTemplate
    type: string
  - name: acrNameTemplate
    type: string
  - name: imagePathPrefix
    type: string
  - name: environments
    type: object
    default:
      - dev
      - qa
      - prod
  - name: imageTagPath
    type: string
    default: ".spec.values.image.tag"

stages:
  - stage: push
    jobs:
    - ${{ each env in parameters.environments }}:
      - template: push.yaml
        parameters:
          poolName: ${{ format(parameters.poolNameTemplate, env) }}
          sourceBranch: ${{ parameters.sourceBranch }}
          environment: ${{ env }}
          serviceName: ${{ parameters.serviceName }}
          azureSubscription: ${{ format(parameters.azureSubscriptionTemplate, env) }}
          acrName: ${{ format(parameters.acrNameTemplate, env) }}
          imagePathPrefix: ${{ parameters.imagePathPrefix }}

  - ${{ each env in parameters.environments }}:
    - stage: deploy_${{ env }}
      jobs:
      - template: deploy.yaml
        parameters:
          poolName: ${{ format(parameters.poolNameTemplate, env) }}
          sourceBranch: ${{ parameters.sourceBranch }}
          environment: ${{ env }}
          serviceName: ${{ parameters.serviceName }}
          imageTagPath: ${{ parameters.imageTagPath }}
          deployTags: false
