parameters:
  - name: serviceName
    type: string
  - name: envs
    type: object
    default:
      - dev
      - qa
      - prod

stages:
  - stage: push_images
    jobs:
    - ${{ each env in parameters.envs }}:
      - template: push_image.yaml
        parameters:
          environment: ${{ env }}
          serviceName: ${{ parameters.serviceName }}

- ${{ each env in parameters.envs }}:
  - stage: deploy_$${{ env }}
    #dependsOn: [Push_containers]
    jobs:
    - template: deploy.yaml
      parameters:
        deployment: Deploy_dev
        environment: $${ env }}
        serviceName: ${{ parameters.serviceName }}
        deployTags: false
