parameters:
  - name: poolNameTemplate
    type: string
  - name: serviceName
    type: string
  - name: envs
    type: object
    default:
      - dev
      - qa
      - prod

stages:
  - stage: push_images
    jobs:
    - ${{ each env in parameters.envs }}:
      - template: push_image.yaml
        parameters:
          poolName: ${{ format(parameters.poolNameTemplate, env) }}
          environment: ${{ env }}
          serviceName: ${{ parameters.serviceName }}


  - ${{ each env in parameters.envs }}:
    - stage: deploy_${{ env }}
      jobs:
      - template: deploy.yaml
        parameters:
          poolName: ${{ format(parameters.poolNameTemplate, env) }}
          environment: ${{ env }}
          serviceName: ${{ parameters.serviceName }}
          deployTags: false
