parameters:
  poolName: ""
  environment: ""
  serviceName: ""
  sourceBranch: "refs/heads/master"
  azureSubscription: ""
  acrName: ""
  imagePathPrefix: ""

jobs:
  - job: push_${{ parameters.environment }}
    condition: and(succeeded(), eq(variables['resources.pipeline.ciPipeline.sourceBranch'], '${{ parameters.sourceBranch }}'))
    displayName: Push ${{ parameters.environment }}
    pool:
      name: ${{ parameters.poolName }}
    continueOnError: false
    steps:
      # Should run for all environments and all branches (master + tags)
      - script: |
          set -e
          shortCommitHash=${sourceVersion:0:7}
          echo "Long commit hash: ${sourceVersion}"
          echo "Short commit hash: ${shortCommitHash}"
          echo "##vso[task.setvariable variable=shortCommitHash]$shortCommitHash"
        displayName: "Generate shortCommitHash (7-digit git hash)"
        env:
          sourceVersion: $(resources.pipeline.ciPipeline.sourceCommit)
          sourceBranch: $(resources.pipeline.ciPipeline.sourceBranch)

      # Only needed for commits to master
      - task: DownloadPipelineArtifact@2
        displayName: "Download container artifact"
        inputs:
          buildType: 'specific'
          project: '$(resources.pipeline.ciPipeline.projectID)'
          definition: '$(resources.pipeline.ciPipeline.pipelineID)'
          preferTriggeringPipeline: true
          targetPath: '$(Pipeline.Workspace)'

      # Should upload to ACR for DEV/QA/PROD
      - task: AzureCLI@2
        displayName: "Push image to ACR"
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          addSpnToEnvironment: true
          workingDirectory: "."
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            set -e
            ARTIFACT_PATH="$(Pipeline.Workspace)/${{ parameters.serviceName }}/${{ parameters.serviceName }}_$(shortCommitHash).tar.gz"
            [[ ! -f $ARTIFACT_PATH ]] && echo "Missing artifact file ($ARTIFACT_PATH) from CI pipeline, did you trigger this pipeline manually?" && exit 1
            IMAGE_ID="${{ parameters.serviceName }}:$(shortCommitHash)"
            IMAGE_ID_FULL="${{ parameters.acrName }}.azure.io/${{ parameters.imagePathPrefix }}/${IMAGE_ID}"
            az acr login -n "${{ parameters.acrName }}"
            docker load < $ARTIFACT_PATH
            docker tag "${IMAGE_ID}" "${IMAGE_ID_FULL}"
            docker push ${IMAGE_FULL_NAME}
