parameters:
  - name: poolVmImage
    type: string
    default: "ubuntu-16.04"
  - name: poolName
    type: string
    default: ""
  - name: environments
    type: object
  - name: gitopsPromotionTag
    type: string
    default: "v0.0.6"
  - name: serviceConnectionTemplate
    type: string
  - name: awsRegion
    type: string
  - name: group
    type: string

stages:
  - stage: push
    jobs:
      - ${{ each env in parameters.environments }}:
          - template: push.yaml
            parameters:
              poolVmImage: ${{ parameters.poolVmImage }}
              poolName: ${{ parameters.poolName }}
              environment: ${{ env.name }}
              serviceConnection: ${{ format(parameters.serviceConnectionTemplate, env.name) }}
              awsRegion: ${{ parameters.awsRegion }}

  - stage: new
    dependsOn: [push]
    jobs:
      - template: new.yaml
        parameters:
          poolVmImage: ${{ parameters.poolVmImage }}
          poolName: ${{ parameters.poolName }}
          gitopsPromotionTag: ${{ parameters.gitopsPromotionTag }}
          group: ${{ parameters.group }}
