pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - script: |
      cd $(mktemp -d)
      git status
      git clone https://github.com/XenitAB/azure-devops-templates
      cd azure-devops-templates
      git remote remove origin
      git remote add origin $(Build.Repository.Uri)
      git push --all origin
